Repository vektorprogrammet/vektorprogrammet, pull requests merged in 2018-09, with the labels that each got.

#985 Render application status on interview response page if already responded
  app/Resources/views/interview/response.html.twig
  src/AppBundle/Controller/InterviewController.php
Labels: PR: Good to Merge

#991 Fix semester "HasActiveAdmission()" function
  src/AppBundle/Entity/Repository/SemesterRepository.php
  src/AppBundle/Entity/Semester.php
Labels: PR: Good to Merge

#989 Autofill room, campus and mapLink when scheduling interviews
  app/DoctrineMigrations/Version20180831172454.php
  src/AppBundle/Entity/Interview.php
  src/AppBundle/Entity/Repository/InterviewRepository.php
  src/AppBundle/Service/InterviewManager.php
Labels: PR: Good to Merge

#984 CoInterviewers can conduct assigned interviews
  app/Resources/views/admission_admin/assigned_table.html.twig
  app/Resources/views/error/control_panel_error.html.twig
  app/Resources/views/interview/assign_co_interview_form.html.twig
  app/config/routing.yml
  src/AppBundle/Controller/InterviewController.php
  src/AppBundle/Service/InterviewManager.php
Labels: PR: Good to Merge

#990 Create a command to send list of scheduled interviews to all interviewers
  app/Resources/views/interview/_schedule_of_interview_line.html.twig
  app/Resources/views/interview/_schedule_of_interviews_status.html.twig
  app/Resources/views/interview/schedule_of_interviews_email.html.twig
  src/AppBundle/Command/SendListOfScheduledInterviewsCommand.php
  src/AppBundle/Entity/Repository/InterviewRepository.php
  src/AppBundle/Service/InterviewManager.php
Labels: PR: Good to Merge

#994 Set default user role to "Assistant"
  src/AppBundle/Entity/User.php
  src/AppBundle/EventSubscriber/DbSubscriber.php
  src/AppBundle/Resources/config/services.yml
Labels: PR: Good to Merge

#1001 Don't send schedule list of completed interviews to coInterviewer
  src/AppBundle/Entity/Repository/ApplicationRepository.php
  src/AppBundle/Entity/Repository/InterviewRepository.php
Labels: PR: Good to Merge

#1010 Ensure user is logged in before accessing /profil/partnere
  app/config/security.yml
Labels: Hotfix

#1012 Update Google GetUser() function
  src/AppBundle/Google/GoogleUsers.php
Labels: Bug

#1013 Suspend G Suite user when demoted to Assistant (unsuspend when promoted to team member)
  src/AppBundle/Google/GoogleUsers.php
  src/AppBundle/Resources/config/services.yml
  src/AppBundle/Service/RoleManager.php
Labels: PR: Good to Merge

#1014 Send mail to applicant created from control panel
  src/AppBundle/Controller/AdmissionAdminController.php
Labels: PR: Good to Merge

#999 Interview reminders
  app/DoctrineMigrations/Version20180905100253.php
  app/Resources/views/interview/accept_interview_reminder_email.html.twig
  src/AppBundle/Command/SendAcceptInterviewReminderCommand.php
  src/AppBundle/Entity/Interview.php
  src/AppBundle/Entity/Repository/InterviewRepository.php
  src/AppBundle/Resources/config/services.yml
  src/AppBundle/Service/InterviewManager.php
Labels: PR: Good to Merge

#1021 Fix interview receipt not being rendered as HTML
  src/AppBundle/EventSubscriber/InterviewSubscriber.php
Labels: Hotfix

#1022 Update NPM packages
  gulpfile.js
  package-lock.json
  package.json
Labels: Security

#1026 Vue Client
  app/AppKernel.php
  app/Resources/assets/scss/app.scss
  app/Resources/assets/scss/modules/page-header.scss
  app/Resources/views/client/index.html.twig
  app/config/automapper.yml
  app/config/config.yml
  app/config/config_dev.yml
  app/config/security.yml
  client/.gitignore
  client/README.md
  client/babel.config.js
  client/config.js
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.vue
  client/src/assets/logo.png
  client/src/components/AdminNav.vue
  client/src/components/AssistantNav.vue
  client/src/components/PageHeader.vue
  client/src/main.js
  client/src/router/index.js
  client/src/services/account.service.js
  client/src/services/http.service.js
  client/src/services/index.js
  client/src/services/staging.service.js
  client/src/store/account.module.js
  client/src/store/index.js
  client/src/store/staging.module.js
  client/src/views/Error403View.vue
  client/src/views/Error404View.vue
  client/src/views/LoginView.vue
  client/src/views/assistant/AssistantBaseView.vue
  client/src/views/assistant/MyPageView.vue
  client/src/views/controlpanel/AdminBaseView.vue
  client/src/views/controlpanel/StagingServerView.vue
  composer.json
  composer.lock
  gulpfile.js
  package-lock.json
  package.json
  src/AppBundle/AutoMapper/UserMap.php
  src/AppBundle/Controller/Api/AccountController.php
  src/AppBundle/Controller/ClientController.php
  src/AppBundle/DataTransferObject/UserDto.php
  src/AppBundle/Entity/Repository/UserRepository.php
  src/AppBundle/Entity/User.php
Labels: On Hold
