Repository vektorprogrammet/vektorprogrammet, pull requests merged in 2018-11, with the labels that each got.

#1059 Info meeting mail
  app/DoctrineMigrations/Version20181101152920.php
  app/Resources/views/admission/application_form.html.twig
  app/Resources/views/admission/info_meeting_email.html.twig
  app/Resources/views/admission_subscriber/subscribe_page.html.twig
  app/Resources/views/assistant/assistants.html.twig
  src/AppBundle/Command/SendInfoMeetingNotificationsCommand.php
  src/AppBundle/Controller/AdmissionSubscriberController.php
  src/AppBundle/Controller/InterviewController.php
  src/AppBundle/Entity/AdmissionNotification.php
  src/AppBundle/Entity/AdmissionSubscriber.php
  src/AppBundle/Entity/Repository/AdmissionNotificationRepository.php
  src/AppBundle/Form/Type/AdmissionSubscriberType.php
  src/AppBundle/Service/AdmissionNotifier.php
  src/AppBundle/Service/EmailSender.php
  src/AppBundle/Service/InterviewManager.php
Labels: PR: Needs Review

#1079 Set drive permission of teams to 'fileOrganizer' instead of 'owner'
  src/AppBundle/Google/GoogleDrive.php
Labels: Bug, PR: Needs Review

#1091 Autowire and Autoconfigure services
  app/config/config.yml
  app/config/event_subscribers.yml
  app/config/forms.yml
  app/config/services.yml
  app/config/services_google.yml
  app/config/twig.yml
  app/config/validators.yml
  src/AppBundle/Controller/AccessRuleController.php
  src/AppBundle/Controller/AdmissionAdminController.php
  src/AppBundle/Controller/AdmissionSubscriberController.php
  src/AppBundle/Controller/ApplicationStatisticsController.php
  src/AppBundle/Controller/ArticleAdminController.php
  src/AppBundle/Controller/AssistantController.php
  src/AppBundle/Controller/AssistantHistoryController.php
  src/AppBundle/Controller/BoardAndTeamController.php
  src/AppBundle/Controller/ContactController.php
  src/AppBundle/Controller/ControlPanelController.php
  src/AppBundle/Controller/ExecutiveBoardController.php
  src/AppBundle/Controller/ExistingUserAdmissionController.php
  src/AppBundle/Controller/GitHubController.php
  src/AppBundle/Controller/HomeController.php
  src/AppBundle/Controller/InterviewController.php
  src/AppBundle/Controller/NewsletterController.php
  src/AppBundle/Controller/PasswordResetController.php
  src/AppBundle/Controller/ProfileController.php
  src/AppBundle/Controller/ProfilePhotoController.php
  src/AppBundle/Controller/ReceiptController.php
  src/AppBundle/Controller/SponsorsController.php
  src/AppBundle/Controller/StandController.php
  src/AppBundle/Controller/StaticContentController.php
  src/AppBundle/Controller/SubscriberController.php
  src/AppBundle/Controller/SurveyController.php
  src/AppBundle/Controller/UserAdminController.php
  src/AppBundle/Controller/UserController.php
  src/AppBundle/EventSubscriber/DbSubscriber.php
  src/AppBundle/EventSubscriber/ImageSubscriber.php
  src/AppBundle/EventSubscriber/TeamInterestSubscriber.php
  src/AppBundle/Resources/config/services.yml
  src/AppBundle/Resources/doc/index.rst
  src/AppBundle/Resources/translations/messages.fr.xlf
  src/AppBundle/Service/EmailSender.php
  src/AppBundle/Service/FileUploader.php
  src/AppBundle/Service/InterviewManager.php
  src/AppBundle/Service/PasswordManager.php
  src/AppBundle/Utils/ReceiptStatistics.php
  tests/AppBundle/Service/AccessControlTest.php
  tests/AppBundle/Service/CompanyEmailMakerTest.php
  tests/AppBundle/Service/RoleManagerTest.php
  tests/AppBundle/Service/SlugMakerTest.php
  tests/AppBundle/Service/SorterTest.php
Labels: PR: Good to Merge

#1101 Team welcome mail
  app/Resources/assets/images/email_images/add_account.png
  app/Resources/assets/images/email_images/signin.png
  app/Resources/assets/images/email_images/vektor_signin.PNG
  app/Resources/assets/images/email_images/vektormail_signin.PNG
  app/Resources/views/team_admin/welcome_google_mail.html.twig
  app/Resources/views/team_admin/welcome_team_membership_mail.html.twig
  src/AppBundle/EventSubscriber/IntroductionEmailSubscriber.php
Labels: PR: Needs Review
