Repository vektorprogrammet/vektorprogrammet, pull requests merged in 2018-08, with the labels that each got.

#905 Log warning to slack when ipinfo fails
  app/Resources/views/admission/application_form.html.twig
  src/AppBundle/Controller/AssistantController.php
  src/AppBundle/Resources/config/services.yml
  src/AppBundle/Service/GeoLocation.php
  src/AppBundle/Tests/Service/GeoLocationTest.php
Labels: PR: Needs Review

#906 Alle søkere får tilgang til brukeren sin. Status på vektorsøknad på "Min side"
  app/Resources/assets/scss/app.scss
  app/Resources/views/admission/admission_email.html.twig
  app/Resources/views/base/header.html.twig
  app/Resources/views/base/user_dropdown.html.twig
  app/Resources/views/interview/response.html.twig
  app/Resources/views/my_page/applications.html.twig
  app/Resources/views/my_page/interview_description.html.twig
  app/Resources/views/my_page/interview_invitation.html.twig
  app/Resources/views/my_page/interview_result.html.twig
  app/Resources/views/my_page/my_page.html.twig
  app/Resources/views/my_page/my_partners.html.twig
  app/Resources/views/profile/profile_header.html.twig
  app/config/security.yml
  app/config/services.yml
  src/AppBundle/Controller/InterviewController.php
  src/AppBundle/Controller/ProfileController.php
  src/AppBundle/Controller/SecurityController.php
  src/AppBundle/Controller/UserController.php
  src/AppBundle/Entity/Application.php
  src/AppBundle/Entity/Interview.php
  src/AppBundle/Entity/Repository/ApplicationRepository.php
  src/AppBundle/Entity/User.php
  src/AppBundle/EventSubscriber/ApplicationSubscriber.php
  src/AppBundle/Model/ApplicationStatus.php
  src/AppBundle/Resources/config/services.yml
  src/AppBundle/Service/ApplicationManager.php
  src/AppBundle/Service/UserRegistration.php
  src/AppBundle/Tests/Availability/AvailabilityFunctionalTest.php
  src/AppBundle/Tests/Controller/SecurityControllerTest.php
Labels: PR: Good to Merge

#909 Update dependencies
  composer.lock
Labels: PR: Good to Merge

#911 Use department city instead of shortName in admission banner on home page
  app/Resources/views/home/index.html.twig
Labels: PR: Good to Merge

#910 Show call to action link on assistant page
  app/Resources/assets/scss/pages/assistants.scss
  app/Resources/views/assistant/assistants.html.twig
  src/AppBundle/Controller/AssistantController.php
  src/AppBundle/Service/FilterService.php
Labels: PR: Good to Merge

#913 Change Department toString to return city
  src/AppBundle/Entity/Department.php
  src/AppBundle/Tests/Controller/AdmissionAdminControllerTest.php
  src/AppBundle/Tests/Controller/SchoolAdminControllerTest.php
Labels: PR: Good to Merge

#914 Hard code "https://vektorprogrammet.no" in admission notification email template
  app/Resources/views/admission/notification_email.html.twig
  app/Resources/views/login/login.html.twig
  src/AppBundle/Controller/AdmissionSubscriberController.php
Labels: PR: Good to Merge

#907 Team interesse: Velge potensielle team under intervju
  app/DoctrineMigrations/Version20180812150217.php
  app/Resources/assets/scss/control_panel.scss
  app/Resources/views/admission_admin/layout.html.twig
  app/Resources/views/admission_admin/teamInterest.html.twig
  app/Resources/views/base/footer.html.twig
  app/Resources/views/common/department_dropdown.html.twig
  app/Resources/views/common/semester_dropdown.html.twig
  app/Resources/views/interview/conduct.html.twig
  app/Resources/views/participant_history/index.html.twig
  app/Resources/views/user_admin/index.html.twig
  src/AppBundle/Controller/AdmissionAdminController.php
  src/AppBundle/Controller/InterviewController.php
  src/AppBundle/DataFixtures/ORM/LoadApplicationData.php
  src/AppBundle/Entity/Application.php
  src/AppBundle/Entity/Repository/TeamRepository.php
  src/AppBundle/Entity/Team.php
  src/AppBundle/Form/Type/ApplicationInterviewType.php
  src/AppBundle/Form/Type/ApplicationPracticalType.php
  src/AppBundle/Tests/Controller/InterviewControllerTest.php
Labels: PR: Good to Merge

#912 Reduce margins between sections on all pages
  app/Resources/assets/scss/app.scss
  app/Resources/assets/scss/pages/about_us_page.scss
  app/Resources/assets/scss/pages/assistants.scss
  app/Resources/assets/scss/pages/teacher.scss
Labels: PR: Good to Merge

#920 Add better team urls
  app/DoctrineMigrations/Version20180813171219.php
  app/Resources/views/contact/index.html.twig
  app/Resources/views/home/index.html.twig
  app/Resources/views/team/team_card.html.twig
  app/Resources/views/team_admin/create_team.html.twig
  app/config/routing.yml
  src/AppBundle/Controller/AssistantController.php
  src/AppBundle/Controller/TeamAdminController.php
  src/AppBundle/Controller/TeamController.php
  src/AppBundle/Entity/Department.php
  src/AppBundle/Entity/Repository/DepartmentRepository.php
  src/AppBundle/Entity/Repository/TeamRepository.php
  src/AppBundle/Entity/Team.php
  src/AppBundle/Tests/Controller/BoardAndTeamControllerTest.php
  src/AppBundle/Tests/Controller/DepartmentControllerTest.php
  src/AppBundle/Tests/Controller/TeamAdminControllerTest.php
Labels: PR: Good to Merge

#923 Sort departments on team page by geolocation
  src/AppBundle/Controller/BoardAndTeamController.php
  src/AppBundle/Service/GeoLocation.php
Labels: PR: Good to Merge

#939 Ignore GeoLocations from certain ASNs
  app/Resources/views/home/admission_banner.html.twig
  app/Resources/views/home/index.html.twig
  app/config/parameters.yml.dist
  src/AppBundle/Controller/HomeController.php
  src/AppBundle/Entity/Repository/DepartmentRepository.php
  src/AppBundle/Resources/config/services.yml
  src/AppBundle/Service/GeoLocation.php
  src/AppBundle/Tests/Service/GeoLocationTest.php
Labels: PR: Reviewed w/ Comments

#945 Add campus field to interview schedule form
  app/DoctrineMigrations/Version20180822200336.php
  app/Resources/views/interview/email.html.twig
  app/Resources/views/interview/preview.html.twig
  app/Resources/views/interview/schedule.html.twig
  app/Resources/views/my_page/interview_description.html.twig
  app/Resources/views/my_page/interview_info.html.twig
  app/Resources/views/my_page/interview_invitation.html.twig
  src/AppBundle/Controller/InterviewController.php
  src/AppBundle/Entity/Interview.php
  src/AppBundle/Form/Type/ScheduleInterviewType.php
  src/AppBundle/Service/InterviewManager.php
Labels: PR: Good to Merge

#949 Make link in team cards more fancy
  app/Resources/assets/scss/pages/team.scss
  app/Resources/views/team/team_card.html.twig
Labels: PR: Good to Merge

#957 Remove email log on exception
  app/config/config_prod.yml
Labels: PR: Good to Merge

#959 Update README.md
  README.md
Labels: PR: Good to Merge

#962 Don't delete team when "not confirmed" is clicked
  app/Resources/views/team_admin/show_applications.html.twig
Labels: PR: Good to Merge
