Repository vektorprogrammet/vektorprogrammet, pull requests merged in 2019-11, with the labels that each got.

#1240 Google gsuite team
  app/DoctrineMigrations/Version20191015091033.php
  src/AppBundle/Command/UpdateTeamMembershipCommand.php
  src/AppBundle/Controller/TeamAdminController.php
  src/AppBundle/Entity/TeamMembership.php
  src/AppBundle/Event/TeamMembershipEvent.php
  src/AppBundle/EventSubscriber/GSuiteSubscriber.php
  src/AppBundle/EventSubscriber/TeamMembershipSubscriber.php
  src/AppBundle/Google/GoogleGroups.php
  src/AppBundle/Service/TeamMembershipService.php
Labels: PR: Good to Merge

#1287 Delete tar inn email og ikke member. Finner derfor ikke hva den skal …
  src/AppBundle/Google/GoogleGroups.php
Labels: PR: Good to Merge

#1300 Update dependencies
  composer.lock
Labels: Security

#1305 Change language choice from radio buttons to dropdown
  src/AppBundle/Form/Type/ApplicationPracticalType.php
Labels: Bug, Easy
