Repository vektorprogrammet/vektorprogrammet, pull requests merged in 2019-10, with the labels that each got.

#1237 Deny access to confidential surveys if not survey_admin
  src/AppBundle/Controller/SurveyController.php
Labels: ASAP, Bug, PR: Needs Review, Security

#1261 Add Node-Sass as a requirement for starting the project
  package-lock.json
  package.json
  src/AppBundle/AssistantScheduling/Webapp/package-lock.json
Labels: Help Wanted, Suggestion

#1272 Sjekk om bruker er aktiv i team før de kan logge inn via SSO
  src/AppBundle/Controller/SsoController.php
Labels: PR: Good to Merge

#1273 Feedback widget size
  app/Resources/views/feedback_admin/feedback_admin_index.html.twig
  app/Resources/views/widgets/feedback_widget.html.twig
Labels: Design, PR: Needs Review

#1280 Parents static
  .gitignore
  app/Resources/assets/images/assistants_foreldre.jpg
  app/Resources/assets/images/vektorassistent.jpg
  app/Resources/assets/scss/pages/parents.scss
  app/Resources/views/base/header.html.twig
  app/Resources/views/parents/parents.html.twig
  app/config/routing.yml
  src/AppBundle/Controller/ParentsController.php
  src/AppBundle/DataFixtures/ORM/LoadStatic_contentData.php
Labels: Help Wanted

#1283 change method used to check for active membership on sso login
  src/AppBundle/Controller/SsoController.php
Labels: ASAP, Bug

#1279 Added delete functionality to feedback
  app/Resources/views/feedback_admin/feedback_admin_list.html.twig
  app/Resources/views/feedback_admin/feedback_admin_show.html.twig
  app/config/routing.yml
  src/AppBundle/Controller/FeedbackController.php
  tests/AppBundle/Controller/FeedbackControllerTest.php
Labels: PR: Needs Review
