Repository vektorprogrammet/vektorprogrammet, pull requests merged in 2019-01, with the labels that each got.

#1122 survey div fix
  app/Resources/views/form/form_div_layout.html.twig
Labels: PR: Good to Merge

#1121 Auto hide forms with no access
  app/Resources/assets/js/access_control.js
Labels: PR: Good to Merge

#1151 Build client with production config
  deploy.sh
  gulpfile.js
Labels: Suggestion

#1158 Implement party API
  app/AppKernel.php
  app/config/config.yml
  app/config/security.yml
  app/config/services.yml
  composer.json
  composer.lock
  src/AppBundle/Controller/Api/PartyController.php
  src/AppBundle/Entity/Application.php
  src/AppBundle/Entity/Repository/ApplicationRepository.php
  src/AppBundle/Entity/School.php
Labels: ASAP
