Repository vektorprogrammet/vektorprogrammet, pull requests merged in 2020-09, with the labels that each got.

#1350 change text to speech url for updated domain
  client/src/views/partypage/PartyPageView.vue
Labels: ASAP, Easy

#1342 Pixel support h2020
  app/Resources/views/admission/application_form.html.twig
  app/Resources/views/assistant/assistants.html.twig
  app/Resources/views/base.html.twig
  app/config/parameters.yml.dist
Labels: PR: Good to Merge

#1374 make getters for start/end date for admission period able to return null
  src/AppBundle/Entity/AdmissionPeriod.php
  src/AppBundle/Entity/PeriodInterface.php
Labels: Bug, Easy

#1386 move content from unused test to existing one with same name
  src/AppBundle/Tests/Entity/AdmissionPeriodEntityUnitTest.php
  tests/AppBundle/Entity/AdmissionPeriodEntityUnitTest.php
Labels: Code Quality, PR: Needs Review

#1384 remove php super global from GeoLocation.php
  src/AppBundle/Service/GeoLocation.php
Labels: Code Quality, PR: Needs Review

#1379 Fix create new request process manually
  src/AppBundle/Controller/AdmissionAdminController.php
  src/AppBundle/Controller/ApplicationStatisticsController.php
  src/AppBundle/Controller/BaseController.php
  src/AppBundle/Controller/CertificateController.php
  src/AppBundle/Controller/ControlPanelController.php
  src/AppBundle/Controller/MailingListController.php
  src/AppBundle/Controller/ParticipantHistoryController.php
  src/AppBundle/Controller/SchoolCapacityController.php
  src/AppBundle/Controller/SocialEventController.php
  src/AppBundle/Controller/StandController.php
  src/AppBundle/Controller/SubstituteController.php
  src/AppBundle/Controller/SurveyController.php
  src/AppBundle/Controller/TodoListController.php
  src/AppBundle/Controller/WidgetController.php
  tests/AppBundle/Availability/AvailabilityFunctionalTest.php
  tests/AppBundle/Controller/MailingListControllerTest.php
Labels: Code Quality

#1373 Edit user 500 error
  src/AppBundle/EventSubscriber/TeamMembershipSubscriber.php
  src/AppBundle/Service/TeamMembershipService.php
Labels: Bug

#1411 Add sonar-cloud to github workflow
  .github/workflows/build.yml
  app/Resources/assets/files/Aarsrapport_2016.pdf
  sonar-project.properties
Labels: Code Quality
