Repository vektorprogrammet/vektorprogrammet, pull requests merged in 2020-10, with the labels that each got.

#1419 Removed unused import in SemesterExtension.php
  src/AppBundle/Twig/Extension/SemesterExtension.php
Labels: PR: Good to Merge

#1417 Fixes #1407
  src/AppBundle/Entity/Repository/SurveyNotificationRepository.php
Labels: PR: Good to Merge, hacktoberfest-accepted

#1395 fix typo
  src/AppBundle/Command/SendAdmissionNotificationsCommand.php
  src/AppBundle/Command/SendInfoMeetingNotificationsCommand.php
  src/AppBundle/DataFixtures/ORM/LoadStatic_contentData.php
Labels: PR: Good to Merge

#1423 Removed unused imports from services.
  src/AppBundle/Service/ApplicationAdmission.php
  src/AppBundle/Service/BetaRedirecter.php
  src/AppBundle/Service/UserGroupCollectionManager.php
Labels: Code Quality, PR: Needs Review, hacktoberfest-accepted

#1420 Update dependencies
  composer.lock
Labels: PR: Good to Merge

#1435 Exclude migrations and bootstrap from sonarcloud scope
  sonar-project.properties
Labels: hacktoberfest-accepted

#1452 Fixed mistakes in tags in two files.
  app/Resources/views/interview/email.html.twig
  app/Resources/views/stand_admin/stand.html.twig
Labels: PR: Good to Merge

#1453 Added two lines two require in composer.json
  composer.json
Labels: PR: Good to Merge

#1449 Deleted indexAction()
  src/AppBundle/Controller/TeamController.php
Labels: PR: Good to Merge

#1450 Removed AboutController.
  src/AppBundle/Controller/AboutController.php
Labels: PR: Good to Merge

#1422 Use imports for exceptions
  src/AppBundle/Controller/AdmissionSubscriberController.php
  src/AppBundle/Controller/ArticleAdminController.php
  src/AppBundle/Controller/InterviewController.php
  src/AppBundle/Controller/InterviewSchemaController.php
  src/AppBundle/Controller/ProfileController.php
  src/AppBundle/Controller/SchoolAdminController.php
  src/AppBundle/Controller/SurveyController.php
  src/AppBundle/Controller/UserGroupCollectionController.php
  src/AppBundle/EventSubscriber/ApplicationSubscriber.php
  src/AppBundle/Service/AccessControlService.php
  src/AppBundle/Service/AdmissionNotifier.php
  src/AppBundle/Service/RoleManager.php
  src/AppBundle/Service/SlackMessenger.php
  src/AppBundle/Service/UserGroupCollectionManager.php
Labels: hacktoberfest-accepted

#1451 Removed unnecessary break-end tag
  app/Resources/views/feedback_admin/feedback_admin_show.html.twig
Labels: PR: Good to Merge, hacktoberfest-accepted

#1454 Replaced <center> with class="text-center"
  app/Resources/views/home/index.html.twig
Labels: PR: Good to Merge, hacktoberfest-accepted

#1397 ContextErrorException -> ErrorException
  src/AppBundle/Service/GeoLocation.php
Labels: PR: Good to Merge

#1425 Removed unused imports in forms.
  src/AppBundle/Form/InterviewNewTimeType.php
  src/AppBundle/Form/Type/AssignInterviewType.php
  src/AppBundle/Form/Type/CreateSemesterType.php
  src/AppBundle/Form/Type/CreateTeamMembershipType.php
  src/AppBundle/Form/Type/CreateUserType.php
  src/AppBundle/Form/Type/FeedbackType.php
  src/AppBundle/Form/Type/ImageGalleryType.php
  src/AppBundle/Form/Type/ScheduleInterviewType.php
  src/AppBundle/Form/Type/SchoolCapacityType.php
Labels: Code Quality, PR: Good to Merge

#1456 Kode mer lesbar i FeedbackController
  src/AppBundle/Controller/FeedbackController.php
Labels: hacktoberfest-accepted

#1426 Optimize imports #1406
  src/AppBundle/Controller/Api/AccountController.php
  src/AppBundle/Controller/ArticleController.php
  src/AppBundle/Controller/FeedbackController.php
  src/AppBundle/Controller/InterviewController.php
  src/AppBundle/Controller/PositionController.php
  src/AppBundle/Controller/ProfileController.php
  src/AppBundle/Controller/ReceiptController.php
  src/AppBundle/Controller/SemesterController.php
  src/AppBundle/Controller/SponsorsController.php
  src/AppBundle/Controller/StandController.php
  src/AppBundle/Controller/TeamAdminController.php
  src/AppBundle/Controller/TeamController.php
  src/AppBundle/Controller/TodoListController.php
  src/AppBundle/Controller/UserAdminController.php
  src/AppBundle/Controller/WidgetController.php
Labels: Code Quality, PR: Good to Merge, hacktoberfest-accepted

#1461 Added new way for running file specific tests to Readme
  README.md
Labels: PR: Good to Merge, hacktoberfest-accepted

#1462 Team member count
  app/Resources/views/team/team_card.html.twig
Labels: PR: Good to Merge, hacktoberfest-accepted

#1459 Changed to norwegian for datetimepicker
  app/Resources/views/common/datetime_picker.html.twig
Labels: PR: Good to Merge, hacktoberfest-accepted

#1466 remove ImageGallery traces
  src/AppBundle/Entity/Repository/ImageGalleryRepository.php
  src/AppBundle/Event/ImageGalleryEvent.php
  src/AppBundle/Form/Type/ImageGalleryType.php
Labels: PR: Good to Merge, hacktoberfest-accepted
