Repository vektorprogrammet/vektorprogrammet, pull requests merged in 2021-02, with the labels that each got.

#1446 Add "louout_on_user_change: true" to firewall options
  .github/CODEOWNERS
  app/config/security.yml
  src/AppBundle/Controller/BaseController.php
  src/AppBundle/Entity/Role.php
  src/AppBundle/Entity/User.php
Labels: PR: Reviewed w/ Comments, hacktoberfest-accepted

#1497 Fix sonarcloud code-smells
  app/Resources/assets/scss/control_panel.scss
  app/Resources/assets/scss/header.scss
  app/Resources/assets/scss/pages/home.scss
  app/Resources/assets/scss/pages/teacher.scss
  client/src/components/Vektorlogo.vue
  client/src/views/Error403View.vue
  client/src/views/Error404View.vue
  client/src/views/assistant/MyPageView.vue
  client/src/views/controlpanel/StagingServerView.vue
  src/AppBundle/AssistantScheduling/Webapp/src/components/Scheduling.vue
  src/AppBundle/DataFixtures/ORM/LoadSchoolData.php
  src/AppBundle/DataFixtures/ORM/LoadUserData.php
Labels: Code Quality

#1496 Remove remaining Image-entity files
  src/AppBundle/Entity/Repository/ImageRepository.php
  src/AppBundle/EventSubscriber/ImageSubscriber.php
  src/AppBundle/Form/Type/EditImageType.php
  src/AppBundle/Form/Type/UploadImageType.php
Labels: Refactor

#1495 Various code improvements
  src/AppBundle/Command/SendAdmissionNotificationsCommand.php
  src/AppBundle/Command/SendInfoMeetingNotificationsCommand.php
  src/AppBundle/Controller/AdmissionAdminController.php
  src/AppBundle/Controller/AdmissionPeriodController.php
  src/AppBundle/Controller/BaseController.php
  src/AppBundle/Controller/CertificateController.php
  src/AppBundle/Controller/InterviewSchemaController.php
  src/AppBundle/Controller/MailingListController.php
  src/AppBundle/Controller/SocialEventController.php
  src/AppBundle/Controller/SurveyNotifierController.php
  src/AppBundle/Controller/TeamApplicationController.php
  src/AppBundle/Entity/AdmissionNotification.php
  src/AppBundle/Entity/Feedback.php
  src/AppBundle/Entity/FieldOfStudy.php
  src/AppBundle/Entity/Repository/AccessRuleRepository.php
  src/AppBundle/Entity/SurveyNotificationCollection.php
  src/AppBundle/Entity/Team.php
  src/AppBundle/Entity/UserGroupCollection.php
  src/AppBundle/EventSubscriber/ReceiptSubscriber.php
  src/AppBundle/Form/Type/ReceiptType.php
  tests/AppBundle/Controller/AccessRuleControllerTest.php
  tests/AppBundle/Controller/ChangeLogControllerTest.php
  tests/AppBundle/Entity/FeedbackEntityUnitTest.php
  tests/AppBundle/Entity/UserEntityUnitTest.php
  tests/AppBundle/Extension/TeamPositionSortExtensionUnitTest.php
  tests/AppBundle/Service/CompanyEmailMakerTest.php
  tests/AppBundle/Service/RoleManagerTest.php
  tests/AppBundle/Service/SlugMakerTest.php
  tests/AppBundle/Service/TodoListTest.php
  tests/AppBundle/Type/CreateDepartmentTest.php
  tests/AppBundle/Type/CreatePositionTest.php
  tests/AppBundle/Type/CreateSchoolTest.php
  tests/AppBundle/Util/TimeUtilTest.php
Labels: Code Quality

#1477 Replace deprecated width="100%" with Bootstrap class w-100
  app/Resources/views/admission_admin/assigned_applications/interview_distribution.html.twig
  app/Resources/views/admission_admin/assigned_table.html.twig
  app/Resources/views/admission_admin/existing_assistants_applications_table.html.twig
  app/Resources/views/admission_admin/interviewed_applications_table.html.twig
  app/Resources/views/admission_admin/new_applications/table.html.twig
  app/Resources/views/admission_admin/teamInterest.html.twig
  app/Resources/views/members/members.html.twig
  app/Resources/views/participant_history/index.html.twig
  app/Resources/views/receipt/my_receipts_table.html.twig
  app/Resources/views/school_admin/assistant_history_table.html.twig
  app/Resources/views/school_admin/school_table.html.twig
  app/Resources/views/social_event/social_event_list.twig
  app/Resources/views/substitute/index.html.twig
  app/Resources/views/user_admin/user.table.html.twig
Labels: PR: Good to Merge
